import type { WrapRestOptions, RestEndpoint, EndpointParameter } from "../types.js";

export function wrapRestApi(options: WrapRestOptions): string {
  const { baseUrl, name, endpoints } = options;

  const toolHandlers = endpoints
    .map((ep) => generateToolHandler(ep, baseUrl))
    .join("\n\n");

  const toolDefinitions = endpoints
    .map((ep) => generateToolDefinition(ep))
    .join(",\n    ");

  return `#!/usr/bin/env node
// Auto-generated MCP server wrapping REST API: ${name}
// Generated by mcptools

import { createServer } from "node:http";

const TOOLS = [
    ${toolDefinitions}
];

function handleRequest(request) {
  const { method, id, params } = request;

  switch (method) {
    case "initialize":
      return {
        jsonrpc: "2.0",
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: { name: "${name}", version: "1.0.0" },
        },
      };

    case "tools/list":
      return { jsonrpc: "2.0", id, result: { tools: TOOLS } };

    case "tools/call":
      return handleToolCall(id, params?.name, params?.arguments ?? {});

    default:
      if (id !== undefined) {
        return {
          jsonrpc: "2.0",
          id,
          error: { code: -32601, message: "Method not found: " + method },
        };
      }
      return null; // notification, no response needed
  }
}

${toolHandlers}

async function handleToolCall(id, toolName, args) {
  try {
    const result = await callTool(toolName, args);
    return {
      jsonrpc: "2.0",
      id,
      result: { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] },
    };
  } catch (error) {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        content: [{ type: "text", text: "Error: " + error.message }],
        isError: true,
      },
    };
  }
}

// stdio transport
let buffer = "";
process.stdin.setEncoding("utf-8");
process.stdin.on("data", async (chunk) => {
  buffer += chunk;
  const lines = buffer.split("\\n");
  buffer = lines.pop() ?? "";

  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const request = JSON.parse(line);
      const response = await handleRequest(request);
      if (response) {
        process.stdout.write(JSON.stringify(response) + "\\n");
      }
    } catch (e) {
      // skip malformed input
    }
  }
});
`;
}

function generateToolDefinition(ep: RestEndpoint): string {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const param of ep.parameters ?? []) {
    properties[param.name] = {
      type: param.type,
      description: param.description,
    };
    if (param.required) {
      required.push(param.name);
    }
  }

  return JSON.stringify(
    {
      name: ep.name,
      description: ep.description,
      inputSchema: {
        type: "object",
        properties,
        required: required.length > 0 ? required : undefined,
      },
    },
    null,
    6
  );
}

function generateToolHandler(ep: RestEndpoint, baseUrl: string): string {
  const pathParams = (ep.parameters ?? []).filter((p) => p.in === "path");
  const queryParams = (ep.parameters ?? []).filter((p) => p.in === "query");
  const bodyParams = (ep.parameters ?? []).filter((p) => p.in === "body");

  let urlExpr = `"${baseUrl}${ep.path}"`;
  for (const p of pathParams) {
    urlExpr = urlExpr.replace(`{${p.name}}`, `\${args.${p.name}}`);
  }

  const queryParts = queryParams
    .map((p) => `args.${p.name} !== undefined ? "${p.name}=" + encodeURIComponent(args.${p.name}) : ""`)
    .join(", ");

  const hasQuery = queryParams.length > 0;
  const hasBody = bodyParams.length > 0 && ep.method !== "GET";

  return `async function call_${ep.name}(args) {
  let url = \`${urlExpr.replace(/"/g, "")}\`;
  ${hasQuery ? `const query = [${queryParts}].filter(Boolean).join("&");
  if (query) url += "?" + query;` : ""}
  const response = await fetch(url, {
    method: "${ep.method}",
    headers: { "Content-Type": "application/json" },
    ${hasBody ? `body: JSON.stringify({ ${bodyParams.map((p) => p.name).join(", ")} }),` : ""}
  });
  if (!response.ok) throw new Error(\`HTTP \${response.status}: \${await response.text()}\`);
  return response.json();
}`;
}

export function generateToolRouter(endpoints: RestEndpoint[]): string {
  const cases = endpoints
    .map((ep) => `    case "${ep.name}": return call_${ep.name}(args);`)
    .join("\n");

  return `async function callTool(name, args) {
  switch (name) {
${cases}
    default:
      throw new Error("Unknown tool: " + name);
  }
}`;
}
