import type { WrapCliOptions, CliSubcommand } from "../types.js";

export function wrapCli(options: WrapCliOptions): string {
  const { command, name, description, subcommands } = options;

  const toolDefinitions = subcommands
    .map((sub) => generateCliToolDefinition(sub))
    .join(",\n    ");

  const toolHandlers = subcommands
    .map((sub) => generateCliToolHandler(sub, command))
    .join("\n");

  return `#!/usr/bin/env node
// Auto-generated MCP server wrapping CLI: ${command}
// ${description}
// Generated by mcptools

import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const TOOLS = [
    ${toolDefinitions}
];

function handleRequest(request) {
  const { method, id, params } = request;

  switch (method) {
    case "initialize":
      return {
        jsonrpc: "2.0",
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: { name: "${name}", version: "1.0.0" },
        },
      };

    case "tools/list":
      return { jsonrpc: "2.0", id, result: { tools: TOOLS } };

    case "tools/call":
      return handleToolCall(id, params?.name, params?.arguments ?? {});

    default:
      if (id !== undefined) {
        return {
          jsonrpc: "2.0",
          id,
          error: { code: -32601, message: "Method not found: " + method },
        };
      }
      return null;
  }
}

async function handleToolCall(id, toolName, args) {
  try {
    const result = await callTool(toolName, args);
    return {
      jsonrpc: "2.0",
      id,
      result: { content: [{ type: "text", text: result }] },
    };
  } catch (error) {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        content: [{ type: "text", text: "Error: " + error.message }],
        isError: true,
      },
    };
  }
}

async function callTool(name, args) {
  switch (name) {
${toolHandlers}
    default:
      throw new Error("Unknown tool: " + name);
  }
}

let buffer = "";
process.stdin.setEncoding("utf-8");
process.stdin.on("data", async (chunk) => {
  buffer += chunk;
  const lines = buffer.split("\\n");
  buffer = lines.pop() ?? "";

  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const request = JSON.parse(line);
      const response = await handleRequest(request);
      if (response) {
        process.stdout.write(JSON.stringify(response) + "\\n");
      }
    } catch (e) {
      // skip malformed input
    }
  }
});
`;
}

function generateCliToolDefinition(sub: CliSubcommand): string {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const arg of sub.args) {
    properties[arg.name] = {
      type: arg.type,
      description: arg.description,
    };
    if (arg.required) {
      required.push(arg.name);
    }
  }

  return JSON.stringify(
    {
      name: sub.name,
      description: sub.description,
      inputSchema: {
        type: "object",
        properties,
        required: required.length > 0 ? required : undefined,
      },
    },
    null,
    6
  );
}

function generateCliToolHandler(sub: CliSubcommand, command: string): string {
  const argMapping = sub.args
    .map((arg) => {
      if (arg.type === "boolean") {
        return `      if (args.${arg.name}) cmdArgs.push("--${arg.name}");`;
      }
      return `      if (args.${arg.name} !== undefined) cmdArgs.push("--${arg.name}", String(args.${arg.name}));`;
    })
    .join("\n");

  return `    case "${sub.name}": {
      const cmdArgs = ["${sub.name}"];
${argMapping}
      const { stdout, stderr } = await execFileAsync("${command}", cmdArgs);
      return stdout + (stderr ? "\\nSTDERR:\\n" + stderr : "");
    }`;
}
